apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # The port that the service will expose inside the cluster
      targetPort: 80 # The port on the container where NGINX is running
      nodePort: 30007 # The port on the node (or Codespace) that will be exposed externally